name: Minimal CMake Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
      fail-fast: true
    defaults:
      run:
        working-directory: support tools/app
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'
      - name: Install OpenGL
        run: sudo apt-get install libgles2-mesa-dev
      - name: Compiler version
        run: gcc --version
      - name: Configure and build (Debug)
        run: |
          cmake --preset multi-ninja-super-test
          cmake --build build/multi-ninja-super-test
      - name: Run tests
        # skip end-to-end tests for now...
        # note: ctest --preset does not work with -D labels (e.g. Continuous,
        # Nightly), instead use `ctest --test-dir <dir> ...`
        run: >
          ctest --preset multi-ninja-super-test -LE slow
      - name: Build and package (Release)
        run: >
          cmake --workflow --preset multi-ninja-super-package-linux